import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header.components";
import UserContextProvider from "@/contexts/user.context";
import { useState } from "react";
import Loading from "./components/loading/loading.component";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amaral-Ecommerce",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Header />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
